interface Point { date: string; value: number | null }
export default function ObservationChart({ title, points, unit }: { title: string; points: Point[]; unit: string }) {
  const valid = points.filter((point): point is { date: string; value: number } => point.value !== null && Number.isFinite(point.value) && Number.isFinite(Date.parse(point.date))).sort((a, b) => a.date.localeCompare(b.date))
  if (!valid.length) return <div className="intelligence-chart"><h3>{title}</h3><p className="admin-empty">관측값 없음 · 0으로 채우지 않습니다.</p></div>
  const observedMax = Math.max(...valid.map(point => point.value))
  const max = Math.max(1, observedMax)
  const start = Date.parse(valid[0].date), end = Date.parse(valid[valid.length - 1].date)
  const x = (date: string) => end === start ? 300 : 20 + (Date.parse(date) - start) / (end - start) * 560
  return <figure className="intelligence-chart"><figcaption><h3>{title}</h3><span>{valid.length}개 관측 · 마지막 {valid[valid.length - 1].value.toLocaleString()} {unit}</span></figcaption><svg viewBox="0 0 600 150" role="img" aria-label={`${title}: ${valid[0].date}부터 ${valid[valid.length - 1].date}까지 실제 관측 ${valid.length}개. 최대 ${observedMax} ${unit}. 아래 관측값 표 제공.`}><line x1="15" x2="585" y1="125" y2="125" stroke="#dce0e6" />{valid.map((point, index) => <g key={`${point.date}:${index}`}><title>{`${point.date}: ${point.value} ${unit}`}</title><line x1={x(point.date)} x2={x(point.date)} y1="125" y2={125 - point.value / max * 105} stroke="#174cff" strokeWidth={Math.max(2, Math.min(16, 450 / valid.length))} /><circle cx={x(point.date)} cy={125 - point.value / max * 105} r="2" fill="#174cff" /></g>)}</svg><div className="chart-range"><span>{valid[0].date.slice(0, 10)}</span><span>{valid[valid.length - 1].date.slice(0, 10)}</span></div><p className="admin-note">실제 시간 간격 · 원천 date/ISO 기준 (Z = UTC) · 미관측 날짜 보간/0 채움 없음 · 증감률 아님</p><details><summary>관측값 표 ({points.length})</summary><table><caption className="sr-only">{title} 원천 관측값</caption><thead><tr><th scope="col">날짜 / 원천</th><th scope="col">{unit}</th></tr></thead><tbody>{points.map((point, index) => <tr key={index}><td>{point.date}</td><td>{point.value === null ? "미수집" : point.value}</td></tr>)}</tbody></table></details></figure>
}
